'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings 自動保存機能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("db\")>  _
        Public ReadOnly Property WorkDbPath() As String
            Get
                Return CType(Me("WorkDbPath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.10;Initial Catalog=334B;User ID=sa;Password=Insat999")>  _
        Public ReadOnly Property DB334B() As String
            Get
                Return CType(Me("DB334B"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.10;Initial Catalog=334BCLUB;User ID=sa;Password=Insat999")>  _
        Public ReadOnly Property DB334BCLUB() As String
            Get
                Return CType(Me("DB334BCLUB"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public ReadOnly Property T_EVENTRET_MonOfs() As Integer
            Get
                Return CType(Me("T_EVENTRET_MonOfs"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-3")>  _
        Public ReadOnly Property T_INFOMATION_CABI_MonOfs() As Integer
            Get
                Return CType(Me("T_INFOMATION_CABI_MonOfs"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public ReadOnly Property T_DIRECTOR_MonOfs() As Integer
            Get
                Return CType(Me("T_DIRECTOR_MonOfs"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-3")>  _
        Public ReadOnly Property T_INFOMATION_CLUB_MonOfs() As Integer
            Get
                Return CType(Me("T_INFOMATION_CLUB_MonOfs"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("log4net.xml")>  _
        Public ReadOnly Property LogConfigFileName() As String
            Get
                Return CType(Me("LogConfigFileName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DbType")>  _
        Public ReadOnly Property RequestItem1() As String
            Get
                Return CType(Me("RequestItem1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("AplTime")>  _
        Public ReadOnly Property RequestItem2() As String
            Get
                Return CType(Me("RequestItem2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ACCOUNT")>  _
        Public ReadOnly Property RequestItem1_Value1() As String
            Get
                Return CType(Me("RequestItem1_Value1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("HOME")>  _
        Public ReadOnly Property RequestItem1_Value2() As String
            Get
                Return CType(Me("RequestItem1_Value2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MAGAZINE")>  _
        Public ReadOnly Property RequestItem1_Value3() As String
            Get
                Return CType(Me("RequestItem1_Value3"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EVENTRET")>  _
        Public ReadOnly Property RequestItem1_Value4() As String
            Get
                Return CType(Me("RequestItem1_Value4"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DataNo")>  _
        Public ReadOnly Property RequestItem1_Value4_01() As String
            Get
                Return CType(Me("RequestItem1_Value4_01"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Answer")>  _
        Public ReadOnly Property RequestItem1_Value4_02() As String
            Get
                Return CType(Me("RequestItem1_Value4_02"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("AnswerLate")>  _
        Public ReadOnly Property RequestItem1_Value4_03() As String
            Get
                Return CType(Me("RequestItem1_Value4_03"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("AnswerEarly")>  _
        Public ReadOnly Property RequestItem1_Value4_04() As String
            Get
                Return CType(Me("RequestItem1_Value4_04"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Online")>  _
        Public ReadOnly Property RequestItem1_Value4_05() As String
            Get
                Return CType(Me("RequestItem1_Value4_05"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Option1")>  _
        Public ReadOnly Property RequestItem1_Value4_06() As String
            Get
                Return CType(Me("RequestItem1_Value4_06"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Option2")>  _
        Public ReadOnly Property RequestItem1_Value4_07() As String
            Get
                Return CType(Me("RequestItem1_Value4_07"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Option3")>  _
        Public ReadOnly Property RequestItem1_Value4_08() As String
            Get
                Return CType(Me("RequestItem1_Value4_08"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Option4")>  _
        Public ReadOnly Property RequestItem1_Value4_09() As String
            Get
                Return CType(Me("RequestItem1_Value4_09"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Option5")>  _
        Public ReadOnly Property RequestItem1_Value4_10() As String
            Get
                Return CType(Me("RequestItem1_Value4_10"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OtherCount")>  _
        Public ReadOnly Property RequestItem1_Value4_11() As String
            Get
                Return CType(Me("RequestItem1_Value4_11"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MagazineDataNo")>  _
        Public ReadOnly Property RequestItem1_Value3_01() As String
            Get
                Return CType(Me("RequestItem1_Value3_01"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Magazine")>  _
        Public ReadOnly Property RequestItem1_Value3_02() As String
            Get
                Return CType(Me("RequestItem1_Value3_02"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BuyDate")>  _
        Public ReadOnly Property RequestItem1_Value3_03() As String
            Get
                Return CType(Me("RequestItem1_Value3_03"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BuyNumber")>  _
        Public ReadOnly Property RequestItem1_Value3_04() As String
            Get
                Return CType(Me("RequestItem1_Value3_04"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MagazinePrice")>  _
        Public ReadOnly Property RequestItem1_Value3_05() As String
            Get
                Return CType(Me("RequestItem1_Value3_05"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MoneyTotal")>  _
        Public ReadOnly Property RequestItem1_Value3_06() As String
            Get
                Return CType(Me("RequestItem1_Value3_06"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Region")>  _
        Public ReadOnly Property RequestItem1_Value3_07() As String
            Get
                Return CType(Me("RequestItem1_Value3_07"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Zone")>  _
        Public ReadOnly Property RequestItem1_Value3_08() As String
            Get
                Return CType(Me("RequestItem1_Value3_08"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ClubCode")>  _
        Public ReadOnly Property RequestItem1_Value3_09() As String
            Get
                Return CType(Me("RequestItem1_Value3_09"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ClubNameShort")>  _
        Public ReadOnly Property RequestItem1_Value3_10() As String
            Get
                Return CType(Me("RequestItem1_Value3_10"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MemberCode")>  _
        Public ReadOnly Property RequestItem1_Value3_11() As String
            Get
                Return CType(Me("RequestItem1_Value3_11"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MemberName")>  _
        Public ReadOnly Property RequestItem1_Value3_12() As String
            Get
                Return CType(Me("RequestItem1_Value3_12"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EditUser")>  _
        Public ReadOnly Property RequestItem1_Value3_13() As String
            Get
                Return CType(Me("RequestItem1_Value3_13"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EditDate")>  _
        Public ReadOnly Property RequestItem1_Value3_14() As String
            Get
                Return CType(Me("RequestItem1_Value3_14"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TOP")>  _
        Public ReadOnly Property RequestItem1_Value5() As String
            Get
                Return CType(Me("RequestItem1_Value5"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LionsAplDB")>  _
        Public ReadOnly Property SQLiteFileName() As String
            Get
                Return CType(Me("SQLiteFileName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(".db3")>  _
        Public ReadOnly Property SQLiteFileEx() As String
            Get
                Return CType(Me("SQLiteFileEx"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("count.txt")>  _
        Public ReadOnly Property CountFile() As String
            Get
                Return CType(Me("CountFile"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ACCOUNTREG")>  _
        Public ReadOnly Property RequestItem1_Value6() As String
            Get
                Return CType(Me("RequestItem1_Value6"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("AccountDate")>  _
        Public ReadOnly Property RequestItem1_Value6_01() As String
            Get
                Return CType(Me("RequestItem1_Value6_01"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Region")>  _
        Public ReadOnly Property RequestItem1_Value6_02() As String
            Get
                Return CType(Me("RequestItem1_Value6_02"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Zone")>  _
        Public ReadOnly Property RequestItem1_Value6_03() As String
            Get
                Return CType(Me("RequestItem1_Value6_03"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ClubCode")>  _
        Public ReadOnly Property RequestItem1_Value6_04() As String
            Get
                Return CType(Me("RequestItem1_Value6_04"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MemberCode")>  _
        Public ReadOnly Property RequestItem1_Value6_05() As String
            Get
                Return CType(Me("RequestItem1_Value6_05"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.LionsAplWeb.My.MySettings
            Get
                Return Global.LionsAplWeb.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
